name: 'build'

on:
  push:
    branches:
    - master

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        run: |
          docker build -t tdtgit/cloudinary-forwarder:latest .
          
  push-to-dockerhub:
    name: 'Push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Push:dockerimage'
        run: |
          docker login -u tdtgit -p ${{ secrets.PAT }}
          docker push tdtgit/cloudinary-forwarder
