name: 'build'

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "tdtgit"
          password: ${{ secrets.PAT }}
          repository: tdtgit/cloudinary-forwarder
          tags: latest