name: 'build'

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: 'Build:dockerimage'
        env:
          IS_PR: ${{ github.EVENT_NAME == 'pull_request' }}
        run: |
          if ${IS_PR}; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF##*/}"
          fi

          if [ "$BRANCH_NAME" == "master" ]; then
            BRANCH_NAME="latest"
          fi
          
          docker login -u tdtgit -p ${{ secrets.PAT }}
          docker buildx build --push --platform linux/arm/v7,linux/arm64,linux/amd64 -t tdtgit/cloudinary-forwarder:$BRANCH_NAME .
